@startuml
component JsonRef.tx <<grammar>> as JsonRefG

component JsonRef <<metamodel>> as JsonRef

component Json <<python_module>> as Json

JsonRef --> "uses" JsonRefG
JsonRef -> "uses" Json
@enduml

