@startuml
component Types.tx <<grammar>> as TypesG
component Data.tx <<grammar>> as DataG
component Flow.tx <<grammar>> as FlowG

component Types <<metamodel>> as Types
component Data <<metamodel>> as Data
component Flow <<metamodel>> as Flow

Data --> "references" Types
Flow --> "references" Data

Types -> "uses" TypesG
Data -> "uses" DataG
Flow -> "uses" FlowG
@enduml

